# -*- coding: utf-8 -*-
"""finalprojectDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eViDK2AK0czcLMeKalkm-7_Tk5gGQ9wt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 3
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 4
from scipy.spatial.distance import cdist
from sklearn.cluster import KMeans
from plotnine import *
from sklearn.decomposition import PCA

# 5
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

# 6
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor

# seed
RSEED = 10

# colors
cmap = 'Greens'

df = pd.read_csv('CO2 Emissions.csv')
df.sha