# -*- coding: utf-8 -*-
"""HW2.2FF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmtkSiTwgD5GNolpHQAcKOQWZ1dkIAJI

# Jamie Parra HW 2.2 Forward Fill Imputation
"""

# how many missing values are in the 'gdp' variable.
import pandas as pd

# Load the Gapminder dataset
data = pd.read_csv('gapminder_data_graphs.csv')
data_1 = data
# Identify and count missing values in the 'gdp' variable
missing_values = data['gdp'].isnull().sum()
print(f"Number of missing values in 'gdp': {missing_values}")

# Summary statistics of 'gdp' before imputation
summary_before_imputation = data['gdp'].describe()

# Compare summary statistics
print("Summary Statistics Before Imputation:")
print(summary_before_imputation)

data['gdp'].fillna(method='ffill', inplace=True)

missing_values_after_imputation = data['gdp'].isnull().sum()
print(f"Number of missing values in 'gdp' after imputation: {missing_values_after_imputation}")

# Summary statistics of 'gdp' after imputation
summary_after_imputation = data['gdp'].describe()

# summary statistics
print("\nSummary Statistics After Forward Fill Imputation:")
print(summary_after_imputation)